### ISSUE TITLE
Latest sync of all.json.gz is broken

### ISSUE THREAD

**Issue by johannesduesing** [bconnorwhite/all-package-names#5]
The [lastet sync](https://github.com/bconnorwhite/all-package-names/blob/743629ac299a4f37c75daac1967cf4dd8b16dfa3/data) of `all.json.gz` seems to me seems broken. When opened with 7ZIP it reports an CRC-Error, when programatically decompressing it in Java i get 

```
java.util.zip.ZipException: Corrupt GZIP trailer
	at java.base/java.util.zip.GZIPInputStream.readTrailer(GZIPInputStream.java:225)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:119)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:106)
```
None of those errors occur with any of the three previous syncs, so i guess this may be a one-time issue with this particular instance (Commit [743629a](https://github.com/bconnorwhite/all-package-names/commit/743629ac299a4f37c75daac1967cf4dd8b16dfa3)). I'm happy just waiting for the next successful sync - just thought i would let you know, maybe there's an underlying issue there.

Thanks for providing this great repository, it helps me a lot!

**Comment by bconnorwhite** [comment]
@johannesduesing this is fixed now, v3 just uses a normal JSON file which is no longer stored in the repo itself
